# Change these first
owner: vitormss # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: UTAD
    url: https://www.utad.pt
  #- name: Google
  #  url: https://www.google.com
  #- name: Wikipedia
  #  url: https://en.wikipedia.org
  #- name: Hacker News
  #  url: https://news.ycombinator.com
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  baseUrl: /upptime # where "repo" is your repository name
  name: UTAD

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
