# Change these first
owner: vitormss # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  #- name: UTAD
  #  url: https://www.utad.pt
  #- name: UTAD Notícias
  #  url: https://noticias.utad.pt
  #- name: UTAD Eventos
  #  url: https://eventos.utad.pt
  #- name: UTAD GescompX
  #  url: https://gescompx.utad.pt
  #- name: UTAD SIGA
  #  url: https://siga.utad.pt
  #- name: Google
  #  url: https://www.google.com
  #- name: Wikipedia
  #  url: https://en.wikipedia.org
  #- name: Hacker News
  #  url: https://news.ycombinator.com
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  #cname: utad.pt # Custom domain CNAME
  baseUrl: /upptime # where "repo" is your repository name
  name: Check Web Site Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
